### ISSUE TITLE
Announce the default `pageLimit` to the user

### ISSUE THREAD

**Issue by fpapado** [fpapado/accessible-pipeline#1]
The default page limit is set to `20`, to avoid accidentally bombing a site. However, this is not surfaced adequately, and can confuse the user, who sees only a few pages crawled. 

## Possible next steps
I think two things could be done:
- Surface this reasoning in the documentation
- Furthermore, if the user has not specified an alternative to the default, print a warning-level "Will run with the default option of...". This will have to be added to the streaming API as well.

**Comment by danielrlc** [comment]
@jetch and I can try this one.

**Comment by fpapado** [comment]
Sold!

**Comment by fpapado** [comment]
Merged in #22 :tada:
