### ISSUE TITLE
Use page.$ instead of cheerio

### ISSUE THREAD

**Issue by fpapado** [fpapado/accessible-pipeline#16]
Back when I started this project, I could not find a way to query the DOM from Puppeteer. Thus, in order to run selectors (to find the anchors), I used cheerio. This needs more data to load, another parser etc. It seems brittle, and I think we can move away from it.

## Possible next steps
- Read the documentation on [page.$()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector)
- Use the page selector in place of cheerio
- Uninstall cheerio and its types

**Comment by ArtemKolichenkov** [comment]
I wanna take this one :)

**Comment by fpapado** [comment]
@ArtemKolichenkov, sounds good!
