### ISSUE TITLE
Add option to skip query parameters

### ISSUE THREAD

**Issue by fpapado** [fpapado/accessible-pipeline#6]
This is similar to the to the option to skip fragment links

Often in websites, a bunch of "equivalent" URLs  use query parameters, either for cache-busting, or for toggling functionality. Those could be skippable via `--ignoreQueryParams`.

## Possible steps
- Create a test case, with fixtures under `test/fixtures/skip-query-parameters`.
- Add the functionality to `runCore`, under `Options`. Implement this check in the decision-making parts ("should visit page" etc.).
- Add the functionality to the `cli`, similarly to `Options`.
- Document the parameters existence in the docs

This list seems long, so we could take them one at a time! If you need help setting up the test cases, I'd love to help :)

**Comment by eevajonnapanula** [comment]
Can I take this one? Thanks! 😊

**Comment by fpapado** [comment]
Sounds good!

**Comment by fpapado** [comment]
Merged in #25 :tada:
