### ISSUE TITLE
Possible bug in ignoring extensions

### ISSUE THREAD

**Issue by fpapado** [fpapado/accessible-pipeline#7]
Spotted in live use by a coworker:

> A bunch of `.pdf`s were crawled, when they shouldn't have, according to parameters.

## How to investigate

We should write tests for this use case.
We'd start by setting up fixtures under `test/fixtures/ignoring-extensions`.

We'd have the following files as fixtures:
- index.html
- document.pdf
- image.jpg
- about.html

index links to all the other files

Then, we should verify that:
- With .pdf as the ignore parameter, `runCore` only crawls index.html, about.html, image.jpg
- With both .pdf and .jpg as ignore parameters, `runCore` only crawls index.html and about.html

Perhaps we should also verify that:
- The CLI passes the ignore parameter correctly. Possibly a unit test with zero/one/two ignores specified. This could be done as an integration test as well, though it might be harder to verify.

**Comment by devinhaughey** [comment]
I would like to take this ticket.

**Comment by fpapado** [comment]
Sounds good!

**Comment by fpapado** [comment]
Merged in #24 :tada:
I'll spin-off the CLI tests to another issue, because it is more complicated than it seemed initially.
